# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lgotm < Formula
  desc "lgotm is a command for generation LGTM image and generated image is copied to clipboard."
  homepage "https://github.com/johnmanjiro13/lgotm"
  version "0.4.3"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/johnmanjiro13/lgotm/releases/download/v0.4.3/lgotm_Darwin_x86_64.tar.gz"
      sha256 "34210afa2b684f27f26076b281983b8cca518f0cad38617f9f97eb480e88e841"
    end
    if Hardware::CPU.arm?
      url "https://github.com/johnmanjiro13/lgotm/releases/download/v0.4.3/lgotm_Darwin_arm64.tar.gz"
      sha256 "d366e7c13b7d89da36f931b62ad5ffae368bbc56b6783561c04e13aac01c771f"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/johnmanjiro13/lgotm/releases/download/v0.4.3/lgotm_Linux_x86_64.tar.gz"
      sha256 "4683b7d0935ed1a17e392d421cb728da1fde69a7ab5bda3b9c6e163936309a1d"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/johnmanjiro13/lgotm/releases/download/v0.4.3/lgotm_Linux_arm64.tar.gz"
      sha256 "487fd3beebdced974b722b03c233ca356a051934922fc232fc3cced998e3a6c0"
    end
  end

  def install
    bin.install "lgotm"
  end

  test do
    system "#{bin}/lgotm version"
  end
end
