# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lgotm < Formula
  desc "lgotm is a command for generation LGTM image and generated image is copied to clipboard."
  homepage "https://github.com/johnmanjiro13/lgotm"
  version "0.4.2"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/johnmanjiro13/lgotm/releases/download/v0.4.2/lgotm_Darwin_x86_64.tar.gz"
      sha256 "78a046a5820f172be4e44ecf7d3b93cce5aeb8ece29afd9276c33193d59b3979"
    end
    if Hardware::CPU.arm?
      url "https://github.com/johnmanjiro13/lgotm/releases/download/v0.4.2/lgotm_Darwin_arm64.tar.gz"
      sha256 "97e18dc558c339febf53d63961382f356dfeb4ab0b6a9ab92a61e08e007660ea"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/johnmanjiro13/lgotm/releases/download/v0.4.2/lgotm_Linux_x86_64.tar.gz"
      sha256 "447a6e7866e86a9011a3158834b26abf383a8b778d0870748d682ecd110e9406"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/johnmanjiro13/lgotm/releases/download/v0.4.2/lgotm_Linux_arm64.tar.gz"
      sha256 "51a8b20b1b4e5bd86bc45f66ec6314e673e1a891733e18d063f3886e47d57ed7"
    end
  end

  def install
    bin.install "lgotm"
  end

  test do
    system "#{bin}/lgotm version"
  end
end
