# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lgotm < Formula
  desc "lgotm is a command for generation LGTM image and generated image is copied to clipboard."
  homepage "https://github.com/johnmanjiro13/lgotm"
  version "0.4.3"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/johnmanjiro13/lgotm/releases/download/v0.4.3/lgotm_Darwin_x86_64.tar.gz"
      sha256 "28e5912b3506e5355bafb1b4ef58e51284afb5f41a4cdf8de006764ddc1cd31a"
    end
    if Hardware::CPU.arm?
      url "https://github.com/johnmanjiro13/lgotm/releases/download/v0.4.3/lgotm_Darwin_arm64.tar.gz"
      sha256 "e5e8723c06c280fbc0fee7a41e8ded4eebce5f20081c92d621988f6609424f6e"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/johnmanjiro13/lgotm/releases/download/v0.4.3/lgotm_Linux_x86_64.tar.gz"
      sha256 "3921fe772843094385b26e208f04434d4a63ba4b9f318142bad71d75fae9b732"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/johnmanjiro13/lgotm/releases/download/v0.4.3/lgotm_Linux_arm64.tar.gz"
      sha256 "a74253c19ba20a77be75179d017297223248ae0d5ac8e0355ad1a6b5c80e3152"
    end
  end

  def install
    bin.install "lgotm"
  end

  test do
    system "#{bin}/lgotm version"
  end
end
